version: 0.8
os: linux

files:
  - source: .
    destination: /home/ubuntu/spring-plus

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu