spring:
  profiles:
    active: ${profile}
  application:
    name: expert
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mysql_id}
    password: ${mysql_pw}
    url: ${db_url}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    url: ${db_url}
    user: ${mysql_id}
    password: ${mysql_pw}
    baseline-on-migrate: true
cloud:
  aws:
    credentials:
      access-key: ${aws_accessKey}
      secret-key: ${aws_secretKey}
    region:
      static: ${aws_region}
    s3:
      bucket: ${aws_bucketName}
    stack:
      auto: false
jwt:
  secret:
    key: ${jwt_secretKey}
