spring:
  application:
    name: expert-develop
  flyway:
    locations: classpath:db/migration, classpath:db/seed
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true



